
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Josue
 */
public class Traductor extends javax.swing.JFrame {
    traduccion t = new traduccion();
    AnalisisTexto At=new AnalisisTexto();
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    /**
     * Creates new form Traductor
     */
    public Traductor() {
        initComponents();
    }
    
    public String AbrirArchivo(File archivo){
        String documento="";
        try{
            entrada=new FileInputStream(archivo);
            int ascci;
            while((ascci=entrada.read())!=-1){
                char caracter=(char)ascci;
                documento+=caracter;
            }   
        }catch(Exception e){
        }
        return documento;
    }
    public  String GuardarArchivo (File archivo, String documento){
        String mensaje=null;
        try{
            salida=new FileOutputStream(archivo);
            byte[] bytxt=documento.getBytes();
            salida.write(bytxt);
            mensaje="Archivo Guardado";
        }catch(Exception e){
        }
        return mensaje;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        btn_procesar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea_trad = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();
        lbl_longitud = new javax.swing.JLabel();
        lbl_Tpalabras = new javax.swing.JLabel();
        lbl_Plt = new javax.swing.JLabel();
        lbl_Ult = new javax.swing.JLabel();
        lbl_Lct = new javax.swing.JLabel();
        lbl_Pp = new javax.swing.JLabel();
        lbl_Pc = new javax.swing.JLabel();
        lbl_Pu = new javax.swing.JLabel();
        lbl_RepA = new javax.swing.JLabel();
        lbl_RepE = new javax.swing.JLabel();
        lbl_RepI = new javax.swing.JLabel();
        lbl_RepO = new javax.swing.JLabel();
        lbl_RepU = new javax.swing.JLabel();
        lbl_palabrasPar = new javax.swing.JLabel();
        lbl_palabrasImpar = new javax.swing.JLabel();
        lbl_long = new javax.swing.JLabel();
        lbl_tp = new javax.swing.JLabel();
        lbl_plt = new javax.swing.JLabel();
        lbl_ult = new javax.swing.JLabel();
        lbl_lct = new javax.swing.JLabel();
        lbl_pp = new javax.swing.JLabel();
        lbl_pc = new javax.swing.JLabel();
        lbl_up = new javax.swing.JLabel();
        lbl_ra = new javax.swing.JLabel();
        lbl_re = new javax.swing.JLabel();
        lbl_ri = new javax.swing.JLabel();
        lbl_ro = new javax.swing.JLabel();
        lbl_ru = new javax.swing.JLabel();
        lbl_ccp = new javax.swing.JLabel();
        lbl_ccip = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mn_Archivo = new javax.swing.JMenu();
        Mn_abrir = new javax.swing.JMenuItem();
        Mn_Guardar = new javax.swing.JMenuItem();
        Mn_GuardarC = new javax.swing.JMenuItem();
        Mn_Editar = new javax.swing.JMenu();
        Mn_Copiar = new javax.swing.JMenuItem();
        Mn_Cortar = new javax.swing.JMenuItem();
        Mn_Pegar = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programación II");

        btn_procesar.setText("Procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        txtarea_trad.setEditable(false);
        jScrollPane1.setViewportView(txtarea_trad);

        txtarea.setColumns(20);
        txtarea.setRows(5);
        jScrollPane2.setViewportView(txtarea);

        lbl_longitud.setText("Longitud del texto:");

        lbl_Tpalabras.setText("Total de palabras: ");

        lbl_Plt.setText("Primera letra del texto: ");

        lbl_Ult.setText("Última letra del texto:");

        lbl_Lct.setText("Letra central del texto:");

        lbl_Pp.setText("Primera palabra:");

        lbl_Pc.setText("Palabra central:");

        lbl_Pu.setText("Última palabra:");

        lbl_RepA.setText("Repeticones de \"A\", \"a\" ó \"á\":");

        lbl_RepE.setText("Repeticones de \"E\", \"e\" ó \"é\":");

        lbl_RepI.setText("Repeticones de \"I\", \"i\" ó \"í\":");

        lbl_RepO.setText("Repeticones de \"O\", \"o\" ó \"ó\":");

        lbl_RepU.setText("Repeticones de \"U\", \"u\" ó \"ú\": ");

        lbl_palabrasPar.setText("Palabras con cantidad de caracteres par: ");

        lbl_palabrasImpar.setText("Palabras con cantidad de caracteres impar: ");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Manejo de cadenas");

        jLabel2.setText("Ingrese un texto o abra un archivo de texto");

        Mn_Archivo.setText("Archivo");

        Mn_abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mn_abrir.setText("Abrir");
        Mn_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_abrirActionPerformed(evt);
            }
        });
        Mn_Archivo.add(Mn_abrir);

        Mn_Guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mn_Guardar.setText("Guardar");
        Mn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_GuardarActionPerformed(evt);
            }
        });
        Mn_Archivo.add(Mn_Guardar);

        Mn_GuardarC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        Mn_GuardarC.setText("Guardar Como");
        Mn_GuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_GuardarCActionPerformed(evt);
            }
        });
        Mn_Archivo.add(Mn_GuardarC);

        jMenuBar1.add(Mn_Archivo);

        Mn_Editar.setText("Editar");

        Mn_Copiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mn_Copiar.setText("Copiar");
        Mn_Copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_CopiarActionPerformed(evt);
            }
        });
        Mn_Editar.add(Mn_Copiar);

        Mn_Cortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mn_Cortar.setText("Cortar");
        Mn_Cortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_CortarActionPerformed(evt);
            }
        });
        Mn_Editar.add(Mn_Cortar);

        Mn_Pegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Mn_Pegar.setText("Pegar");
        Mn_Pegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mn_PegarActionPerformed(evt);
            }
        });
        Mn_Editar.add(Mn_Pegar);

        jMenuBar1.add(Mn_Editar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Pu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_up, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_Ult)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_ult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_Lct)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_lct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_Tpalabras)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_tp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_longitud)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_long, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_Plt)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_plt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_Pp)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_pp, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_Pc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_pc, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_palabrasPar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_ccp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_RepI)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_ri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(14, 14, 14))
                                            .addComponent(lbl_palabrasImpar))
                                        .addComponent(lbl_ccip, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_RepU)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_ru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_RepO)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_ro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_RepE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_re, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lbl_RepA)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_ra, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(btn_procesar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel1)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_procesar)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_long, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ra, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_longitud)
                        .addComponent(lbl_RepA)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_re, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Tpalabras)
                        .addComponent(lbl_RepE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_ri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Plt)
                            .addComponent(lbl_RepI)))
                    .addComponent(lbl_plt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_ro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Ult)
                        .addComponent(lbl_RepO))
                    .addComponent(lbl_ult, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_lct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ru, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Lct)
                        .addComponent(lbl_RepU)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_pp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Pp)
                            .addComponent(lbl_palabrasPar)))
                    .addComponent(lbl_ccp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_pc, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ccip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Pc)
                        .addComponent(lbl_palabrasImpar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Pu)
                    .addComponent(lbl_up, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
        // TODO add your handling code here:
        String texto=this.txtarea.getText();
        this.txtarea_trad.setText(t.traducir(texto));
        this.lbl_long.setText(At.tamaño(texto));
        this.lbl_tp.setText(At.totalpalabras(texto));
        this.lbl_plt.setText(At.PrimeraL(texto));
        this.lbl_ult.setText(At.UltimaL(texto));
        this.lbl_lct.setText(At.LetraCen(texto));
        this.lbl_pp.setText(At.PrimeraP(texto));
        this.lbl_pc.setText(At.PalabraC(texto));
        this.lbl_up.setText(At.UltimaP(texto));
        this.lbl_ra.setText(At.LetrasA(texto));
        this.lbl_re.setText(At.LetrasE(texto));
        this.lbl_ri.setText(At.LetrasI(texto));
        this.lbl_ro.setText(At.LetrasO(texto));
        this.lbl_ru.setText(At.LetrasU(texto));
        this.lbl_ccp.setText(At.PalabrasPar(texto));
        this.lbl_ccip.setText(At.PalabrasImpar(texto));
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void Mn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_GuardarActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("txt")){
                String Documento=this.txtarea.getText();
                String mensaje=GuardarArchivo(archivo,Documento);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(null, mensaje);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Guardar Documento de Texto");
            }
        }
    }//GEN-LAST:event_Mn_GuardarActionPerformed

    private void Mn_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_abrirActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null, "abrir")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.canRead()){
                if(archivo.getName().endsWith("txt")){
                    String documento=AbrirArchivo(archivo);
                    this.txtarea.setText(documento);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");
                }
            }
        }
    }//GEN-LAST:event_Mn_abrirActionPerformed

    private void Mn_GuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_GuardarCActionPerformed
        // TODO add your handling code here:
        if(seleccionar.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
            archivo=seleccionar.getSelectedFile();
            if(archivo.getName().endsWith("txt")){
                String Documento=this.txtarea.getText();
                String mensaje=GuardarArchivo(archivo,Documento);
                if(mensaje!=null){
                    JOptionPane.showMessageDialog(null, mensaje);
                }else{
                    JOptionPane.showMessageDialog(null, "Archivo No Compatible");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Guardar Documento de Texto");
            }
        }
        
    }//GEN-LAST:event_Mn_GuardarCActionPerformed

    private void Mn_CopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_CopiarActionPerformed
        // TODO add your handling code here:
        this.txtarea.copy();
    }//GEN-LAST:event_Mn_CopiarActionPerformed

    private void Mn_CortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_CortarActionPerformed
        // TODO add your handling code here:
        this.txtarea.cut();
    }//GEN-LAST:event_Mn_CortarActionPerformed

    private void Mn_PegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mn_PegarActionPerformed
        // TODO add your handling code here:
        this.txtarea.paste();
    }//GEN-LAST:event_Mn_PegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Traductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Traductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mn_Archivo;
    private javax.swing.JMenuItem Mn_Copiar;
    private javax.swing.JMenuItem Mn_Cortar;
    private javax.swing.JMenu Mn_Editar;
    private javax.swing.JMenuItem Mn_Guardar;
    private javax.swing.JMenuItem Mn_GuardarC;
    private javax.swing.JMenuItem Mn_Pegar;
    private javax.swing.JMenuItem Mn_abrir;
    private javax.swing.JButton btn_procesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Lct;
    private javax.swing.JLabel lbl_Pc;
    private javax.swing.JLabel lbl_Plt;
    private javax.swing.JLabel lbl_Pp;
    private javax.swing.JLabel lbl_Pu;
    private javax.swing.JLabel lbl_RepA;
    private javax.swing.JLabel lbl_RepE;
    private javax.swing.JLabel lbl_RepI;
    private javax.swing.JLabel lbl_RepO;
    private javax.swing.JLabel lbl_RepU;
    private javax.swing.JLabel lbl_Tpalabras;
    private javax.swing.JLabel lbl_Ult;
    private javax.swing.JLabel lbl_ccip;
    private javax.swing.JLabel lbl_ccp;
    private javax.swing.JLabel lbl_lct;
    private javax.swing.JLabel lbl_long;
    private javax.swing.JLabel lbl_longitud;
    private javax.swing.JLabel lbl_palabrasImpar;
    private javax.swing.JLabel lbl_palabrasPar;
    private javax.swing.JLabel lbl_pc;
    private javax.swing.JLabel lbl_plt;
    private javax.swing.JLabel lbl_pp;
    private javax.swing.JLabel lbl_ra;
    private javax.swing.JLabel lbl_re;
    private javax.swing.JLabel lbl_ri;
    private javax.swing.JLabel lbl_ro;
    private javax.swing.JLabel lbl_ru;
    private javax.swing.JLabel lbl_tp;
    private javax.swing.JLabel lbl_ult;
    private javax.swing.JLabel lbl_up;
    private javax.swing.JTextArea txtarea;
    private javax.swing.JTextPane txtarea_trad;
    // End of variables declaration//GEN-END:variables
}
